version: '3'

vars:
  BINARY_NAME: weChatGPT

tasks:
  clean:
    cmds:
      - rm -rf dist
      - mkdir -p dist
  build:
    label: build-{{.TASK}}
    cmds:
      - |
        GOOS={{.GOOS}} GOARCH={{.GOARCH}} GOARM={{.GOARM}} GOMIPS={{.GOMIPS}} \
        CGO_ENABLED=0 \
        go build -trimpath -o ./dist/{{.BINARY_NAME}} \
        -ldflags "-w -s -buildid="
  linux-386:
    cmds:
      - task: build
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: 386
        }
  linux-amd64:
    cmds:
      - task: build
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: amd64
        }
  default:
    cmds:
      - task: clean
      - task: linux-amd64